services:
    setNewReference:
      class: Ecommerce\EcommerceBundle\Services\GetReference
      arguments: [@security.context, @doctrine.orm.entity_manager]

    app.twig_extension:
        class: Ecommerce\EcommerceBundle\Twig\Extension\TvaExtension
        public: false
        tags:
            - { name: twig.extension }

    redirectionListener:
        class: Ecommerce\EcommerceBundle\Listener\RedirectionListener
        arguments: [@service_container, @session]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
