# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.twig_extension:
        class: Ecommerce\EcommerceBundle\Twig\Extension\TvaExtension
        public: false
        tags:
            - { name: twig.extension }
