factures:
    path: /profile/factures
    defaults: { _controller: UtilisateursBundle:Utilisateurs:facture }

facturesPDF:
    path: /profile/factures/pdf/{id}
    defaults: { _controller: UtilisateursBundle:Utilisateurs:facturePDF }